version: "3.4"

volumes:
  ui_volume:
  files:

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - application-api
      - application-ui
    ports:
      - 7800:7800

  application-api:
    build: application-api
    image: application-api
    restart: "no"
    volumes:
      - ./application-api/:/app
      - files:/files
    ports:
      - 7777:7777
    depends_on:
      database:
        condition: "service_healthy"
      flyway:
        condition: "service_started"
    env_file:
      - project.env
    deploy:
      replicas: 1

  application-ui:
    build: application-ui
    image: application-ui
    restart: "no"
    volumes:
      - ./application-ui/:/app
      - ui_volume:/app/node_modules
    expose:
      - 3000
    depends_on:
      - application-api

  database:
    container_name: database-server-dab-p1-76ac4c9b-7b75-434d-bded-44f67873ca29
    image: postgres:14.1
    restart: "no"
    expose:
      - 5432
    env_file:
      - project.env
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "$POSTGRES_USER", "-d", "$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 3

  flyway:
    image: flyway/flyway:9.11.0-alpine
    depends_on:
      - database
    volumes:
      - ./flyway/sql/:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate
    env_file:
      - project.env