version: "3.4"

volumes:
  astro_node_modules:
  ui_volume:

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - application-api
      - application-ui
    ports:
      - 7800:7800

  application-api:
    build: application-api
    image: application-api
    restart: "no"
    volumes:
      - ./application-api/:/app
    expose:
      - "7777:7777"
    depends_on:
      - database
      - flyway
    env_file:
      - project.env
    deploy:
      replicas: 2

  application-ui:
    build: application-ui
    image: application-ui
    restart: "no"
    volumes:
      - ./application-ui/:/app
      - ui_volume:/app/node_modules
    expose:
      - 3000
    depends_on:
      - application-api

  database:
    container_name: database-server-dab-p1-76ac4c9b-7b75-434d-bded-44f67873ca29
    image: postgres:14.1
    restart: "no"
    expose:
      - 5432
    env_file:
      - project.env

  flyway:
    image: flyway/flyway:9.11.0-alpine
    depends_on:
      - database
    volumes:
      - ./flyway/sql/:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate
    env_file:
      - project.env